#!/bin/bash

export DATABASE_TYPE=${DATABASE_TYPE:-json}
export DATABASE_URL=${DATABASE_URL:-$HOME/.knife.json}
export PORT=${PORT:-8000}

gunicorn knife.__main__:APP \
    --access-logfile - \
    --access-logformat '%(h)s %(t)s "%(r)s" %(s)s %(L)ss' \
    -b 0.0.0.0:$PORT
